import { readFileSync } from "fs";
import { join } from "path";

// Load WordPress → Next.js redirect map (generated by scripts/convert-wp-posts.mjs)
let wpRedirects = [];
try {
  const raw = readFileSync(join(process.cwd(), "scripts", "redirects.json"), "utf-8");
  wpRedirects = JSON.parse(raw);
} catch {
  // Redirects file may not exist yet before first conversion
}

/** @type {import('next').NextConfig} */
const nextConfig = {
  eslint: {
    // Lint is run separately in CI; don't block production builds
    ignoreDuringBuilds: true,
  },

  images: {
    // All blog images are now served locally from /public/images/blog/
    // No remote patterns needed
  },

  async redirects() {
    return wpRedirects.map((r) => ({
      source: r.source,
      destination: r.destination,
      permanent: true, // 301 redirect — preserves SEO juice
    }));
  },
};

export default nextConfig;
