import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import Breadcrumbs from "@/components/Breadcrumbs";
import { JsonLd } from "@/components/JsonLd";
import { BUSINESS, SERVICE_AREAS } from "@/lib/constants";
import { cityRef } from "@/lib/cities";
import { CUSTOM_WINDOW_TREATMENTS } from "@/lib/schema";
const url = `${BUSINESS.url}/products/aluminum-shutters`;
const faqs = [
  { q: "What are Weatherwell Elite shutters?", a: "Weatherwell Elite is TWO’s architectural aluminum shutter system for exterior and interior applications. Luxe Window Works helps you select the configuration, measures your openings and professionally installs your custom shutters in North Idaho." },
  { q: "Can the panels move out of the way?", a: "Depending on the opening, Elite can be configured as sliding, sliding bi-fold, hinged, fixed or Bahama-style panels. We check the space for tracks, panel stacking and mounting before recommending a layout." },
  { q: "How much do custom aluminum shutters cost?", a: "The price depends on opening dimensions, panel configuration, finish and installation requirements. A free consultation lets us measure the space and provide a project-specific quote, including professional installation." },
  { q: "Can I use them to add privacy to a covered patio?", a: "Yes. Adjustable louvers let you change the balance of privacy, light and airflow. We look at sightlines from neighboring homes and how you use the space before planning the panels." },
  { q: "Will shutters turn my patio into an insulated room?", a: "No. Aluminum shutters provide adjustable screening; they are not an insulated, airtight window system. We will discuss the exposure and intended use of your space so expectations match the installation." },
  { q: "Where does Luxe Window Works install them?", a: "We provide consultations, measurements and installation in Post Falls, Coeur d’Alene, Hayden, Rathdrum, Sandpoint and surrounding North Idaho communities. Our workmanship is backed by our lifetime installation guarantee; manufacturer product warranty terms are separate." },
];
export const metadata: Metadata = {
  title: "Weatherwell Elite Aluminum Shutters | North Idaho | Luxe Window Works",
  description: "Custom Weatherwell Elite aluminum shutters for patios, covered decks and interiors. Photos and free in-home consultations from Luxe Window Works in North Idaho.",
  alternates: { canonical: url },
  openGraph: { title: "Weatherwell Elite | Luxe Window Works", description: "More privacy. Adjustable light. An outdoor space that feels finished.", url, images: ["/images/weatherwell-elite/IMG_1086.jpeg"] },
};
export default function AluminumShutters() {
  return <>
    <JsonLd data={[{ "@context": "https://schema.org", "@type": "Service", "@id": `${url}#service`, name: "Custom Aluminum Shutters Service", serviceType: CUSTOM_WINDOW_TREATMENTS, url, provider: { "@id": `${BUSINESS.url}/#business` }, areaServed: SERVICE_AREAS.map(a => cityRef(a.name)), description: "Free in-home consultation, product selection, custom measurement and professional installation of TWO Weatherwell Elite aluminum shutters in North Idaho." }, { "@context": "https://schema.org", "@type": "FAQPage", "@id": `${url}#faq`, mainEntity: faqs.map(f => ({ "@type": "Question", name: f.q, acceptedAnswer: { "@type": "Answer", text: f.a } })) }]} />
    <Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "TWO Collection", href: "/products/two" }, { label: "Weatherwell Elite" }]} />
    <section className="relative bg-charcoal text-white min-h-[630px] flex items-end"><Image src="/images/weatherwell-elite/IMG_1086.jpeg" alt="Dark Weatherwell Elite aluminum shutters on a modern home" fill priority sizes="100vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-r from-black/85 via-black/60 to-black/15" /><div className="container-luxe relative py-16 md:py-24"><div className="max-w-2xl"><p className="uppercase tracking-[.2em] text-xs text-white">Luxe Window Works · TWO Weatherwell Elite</p><h1 className="font-serif text-4xl sm:text-5xl md:text-6xl leading-[1.1] mt-5">An outdoor space<br />that feels <em>finished.</em></h1><p className="text-lg text-white leading-relaxed mt-7 max-w-xl">Custom aluminum shutters bring adjustable privacy, light and airflow to patios, covered decks and distinctive interiors. Designed around your space. Measured and installed by Luxe Window Works.</p><div className="flex flex-wrap gap-3 mt-8"><Link href="/book" className="rounded-full bg-cream text-charcoal px-6 py-4 font-semibold">Book a Free Consultation</Link><a href="#configurations" className="rounded-full border border-white/70 bg-black/20 text-white px-6 py-4">Explore the Possibilities ↓</a></div></div></div></section>
    <section className="container-luxe py-16 md:py-24"><div className="grid lg:grid-cols-[1fr_1.2fr] gap-10 lg:gap-20"><h2 className="font-serif text-3xl sm:text-4xl text-charcoal">Keep the view.<br />Choose the privacy.</h2><div className="text-lg leading-relaxed text-warm-gray-700"><p>Some afternoons, you want everything open. Other times, you want a little distance from the neighbors or a break from the sun. Weatherwell Elite gives your outdoor space that flexibility.</p><p className="mt-5">Start with how you want to use the space. We’ll work through the panel layout, finish and mounting details with you, then take care of the custom measurements and installation.</p></div></div></section>

    <section id="configurations" className="container-luxe py-16 md:py-24 scroll-mt-24"><div className="max-w-2xl mb-10"><p className="uppercase tracking-[.2em] text-xs text-warm-gray-700">Designed around the opening</p><h2 className="font-serif text-3xl sm:text-4xl text-charcoal mt-4">Open, close, slide or fold.</h2><p className="mt-5 text-warm-gray-700 leading-relaxed">Elite offers fixed, hinged, sliding, sliding bi-fold and Bahama configurations, with powder-coated finishes. The right choice depends on the opening and how you want the panels to move.</p></div><div className="grid md:grid-cols-3 gap-6">{[{ image: "IMG_1086.jpeg", title: "Make room for movement", text: "Plan where panels will stack and how you’ll move between spaces." }, { image: "IMG_1190.jpeg", title: "Find your level of privacy", text: "Adjust the louvers as light and sightlines change throughout the day." }, { image: "IMG_5258.jpeg", title: "Finish the architecture", text: "Choose a look that works with the posts, trim and materials already in your space." }].map(x => <article key={x.title}><div className="relative aspect-[4/3] rounded-xl overflow-hidden"><Image src={`/images/weatherwell-elite/${x.image}`} alt={x.title + " with Weatherwell Elite aluminum shutters"} fill sizes="(max-width: 768px) 100vw, 33vw" className="object-cover" /></div><h3 className="font-serif text-2xl text-charcoal mt-5">{x.title}</h3><p className="mt-3 text-warm-gray-700 leading-relaxed">{x.text}</p></article>)}</div></section>
    <section className="bg-linen py-16"><div className="container-luxe grid md:grid-cols-2 gap-8 items-center"><div className="relative aspect-[4/3] rounded-xl overflow-hidden"><Image src="/images/weatherwell-elite/IMG_1195.jpeg" alt="Exterior view of a screened patio fitted with aluminum shutter panels" fill sizes="(max-width: 768px) 100vw, 50vw" className="object-cover" /></div><div><h2 className="font-serif text-3xl text-charcoal">A good fit starts with a visit.</h2><p className="mt-5 text-warm-gray-700 leading-relaxed">Bring us your ideas—or simply show us the spot you’d like to enjoy more. We’ll assess the opening, talk through the options and prepare a clear quote. No guessing at dimensions or figuring out installation on your own.</p><Link href="/book" className="inline-block mt-7 rounded-full bg-charcoal text-white px-7 py-4">Plan My Project</Link></div></div></section>
    <section className="container-luxe max-w-4xl py-16 md:py-24"><h2 className="font-serif text-3xl sm:text-4xl text-charcoal mb-8">Questions about aluminum shutters</h2>{faqs.map(f => <details key={f.q} className="border-b border-warm-gray-200 py-5"><summary className="cursor-pointer text-lg font-medium text-charcoal pr-4">{f.q}</summary><p className="mt-4 text-warm-gray-700 leading-relaxed">{f.a}</p></details>)}<p className="mt-8 text-sm text-warm-gray-700">Product configuration information: <a href="https://two-usa.com/weatherwell-elite/" target="_blank" rel="noopener noreferrer" className="underline">TWO Weatherwell Elite</a>. We confirm specifications for your project before ordering.</p></section>
    <section className="bg-charcoal text-white py-16 md:py-20 text-center"><div className="container-luxe max-w-3xl"><p className="uppercase tracking-[.2em] text-xs">Luxe Window Works · North Idaho</p><h2 className="font-serif text-3xl sm:text-4xl mt-5">Let’s make more of your space.</h2><p className="text-lg mt-5 text-white/85">Personal guidance, professional installation and one local person to call.</p><Link href="/book" className="inline-block mt-8 rounded-full bg-cream text-charcoal font-semibold px-8 py-4">Book a Free Consultation</Link><p className="mt-6"><Link href="/products/two" className="underline underline-offset-4">Explore the full TWO collection →</Link></p></div></section>
  </>;
}
