export interface ProductPageData {
  slug: string;
  name: string;
  headline: string;
  subheadline: string;
  problem: string;
  solution: string;
  expertInsight: string;
  features: string[];
  idealFor: string[];
  localContext: string;
  metaTitle: string;
  metaDescription: string;
}

export const productPages: Record<string, ProductPageData> = {
  "cellular-shades": {
    slug: "cellular-shades",
    name: "Cellular Shades",
    headline: "Tired of Watching Your Energy Bills Climb Every Season?",
    subheadline: "Cellular shades are the most energy-efficient window covering available — and in Northern Idaho, that matters more than most places.",
    problem: "Northern Idaho doesn't do moderate weather. January mornings hit single digits. July afternoons push into the 90s. And through all of it, your windows are the weakest link in your home's insulation. Single-pane windows in older Coeur d'Alene homes bleed heat all winter long. Even newer double-pane windows in Post Falls subdivisions let more energy escape than most homeowners realize.",
    solution: "Cellular shades — sometimes called honeycomb shades — use a unique structure of air pockets that act as insulation right at the window. The honeycomb cells trap air, creating a barrier between the extreme outdoor temperatures and your living space. Available in single, double, or triple-cell designs, with options from sheer light-filtering to complete blackout.",
    expertInsight: "After nearly 20 years of installing these, here's what most companies won't tell you: the cell size matters more than most people think. A 3/4-inch double cell is the sweet spot for most Northern Idaho homes — it gives you substantial insulation without looking bulky. And if you have large windows facing the lake or the mountains, a top-down/bottom-up option lets you keep your view while still insulating the lower portion of the window. I've installed these in everything from 1960s ranch homes in Coeur d'Alene to brand-new builds in Rathdrum, and the difference in comfort is something homeowners notice immediately.",
    features: [
      "Honeycomb cell structure traps air for superior insulation",
      "Available in single, double, and triple cell options",
      "Light-filtering to full blackout fabric choices",
      "Top-down/bottom-up operation available",
      "Cordless and motorized options for child and pet safety",
      "Extensive color and texture range to match any decor",
    ],
    idealFor: [
      "Bedrooms where temperature control and light blocking matter",
      "Older homes with single-pane windows that need extra insulation",
      "Living rooms with large windows facing extreme sun or cold",
      "Anyone looking to reduce energy bills year-round",
      "Homes with kids or pets (cordless options eliminate safety concerns)",
    ],
    localContext: "In Northern Idaho, cellular shades aren't a luxury — they're practically a necessity. The temperature swings between seasons here are brutal on energy bills. Homeowners in Hayden and Rathdrum with newer construction often assume their windows are efficient enough, but adding cellular shades can make a noticeable difference in both comfort and monthly costs.",
    metaTitle: "Cellular Shades in Northern Idaho | Energy Efficient Window Treatments",
    metaDescription: "Custom cellular shades for Northern Idaho homes. The most energy-efficient window covering for Coeur d'Alene, Post Falls, Hayden. Free in-home consultation with nearly 20 years installer expertise.",
  },
  "solar-shades": {
    slug: "solar-shades",
    name: "Solar Shades",
    headline: "Love Your View but Hate the Glare?",
    subheadline: "Solar shades let you keep the scenery while blocking the UV rays, heat gain, and glare that come with it.",
    problem: "Living in Northern Idaho means incredible views — Coeur d'Alene Lake, the Bitterroot Range, sunsets over the Rathdrum Prairie. But those west-facing and south-facing windows that give you those views also bring intense afternoon glare, UV damage to your furniture and floors, and serious heat gain in summer. You shouldn't have to choose between your view and your comfort.",
    solution: "Solar shades are engineered to reduce glare and block UV rays while maintaining your outward visibility. They work like sunglasses for your windows — you can still see out, but the harsh effects of direct sunlight are dramatically reduced. Available in different openness factors (typically 1% to 14%), allowing you to choose exactly how much light and visibility you want.",
    expertInsight: "The number one mistake I see people make with solar shades is choosing the wrong openness factor. A 3% is great for south-facing windows that get hammered with direct sun — it blocks more while still letting you see out. A 10% works better for north-facing windows where you want maximum view with light UV protection. And here's something most people don't realize: the fabric color matters as much as the openness percentage. Darker fabrics reduce glare better and give you better outward visibility, while lighter fabrics reflect more heat. For lake-facing homes in Coeur d'Alene, I usually recommend a dark charcoal in 5% — it cuts the glare off the water beautifully while keeping the view crystal clear.",
    features: [
      "UV protection up to 99% depending on openness factor",
      "Maintains outward visibility while reducing glare",
      "Multiple openness factors from 1% to 14%",
      "Reduces heat gain through windows",
      "Protects furniture, floors, and artwork from UV fading",
      "Available in motorized options for hard-to-reach windows",
    ],
    idealFor: [
      "Lake-facing homes in Coeur d'Alene and Sandpoint",
      "South and west-facing windows with intense afternoon sun",
      "Home offices where screen glare is a problem",
      "Rooms with hardwood floors or furniture you want to protect",
      "Anyone who wants light control without losing their view",
    ],
    localContext: "If you live on the lake or anywhere with western exposure in Northern Idaho, solar shades should be near the top of your list. The summer sun here doesn't set until after 9 PM, and that low-angle evening light creates intense glare that standard curtains can't handle without blocking everything. Solar shades solve this elegantly.",
    metaTitle: "Solar Shades in Northern Idaho | Glare Reduction for Lake Views",
    metaDescription: "Custom solar shades for Northern Idaho homes. Reduce glare and UV damage while keeping your lake and mountain views. Serving Coeur d'Alene, Post Falls, Sandpoint. Free consultation.",
  },
  "roller-shades": {
    slug: "roller-shades",
    name: "Roller Shades",
    headline: "Clean Lines. Simple Function. No Fuss.",
    subheadline: "Roller shades deliver a sleek, modern look that works with any design style — without overcomplicating things.",
    problem: "Not every window needs a complex treatment. Sometimes you want something clean, functional, and understated that doesn't compete with your architecture or decor. But 'simple' doesn't have to mean cheap or boring — and it definitely shouldn't mean poorly made or poorly fitted.",
    solution: "Roller shades are exactly what they sound like — a single piece of fabric that rolls up neatly into a small cassette at the top of your window. What makes them special is the range of fabrics, textures, and opacity levels available, from completely sheer to total blackout. The result is a streamlined look that works in contemporary homes, traditional spaces, and everything in between.",
    expertInsight: "I've been installing roller shades for nearly two decades, and the technology has come a long way. The cassette systems now are sleek and barely visible. The fabrics are incredible — you can get textures that look like linen or woven grass cloth in a roller shade format. The key is getting the measurement right. A roller shade that's even 1/4 inch off shows it, because there's nowhere to hide the gap. That precision is where my experience makes the biggest difference — especially on windows that aren't perfectly square, which is more common than you'd think in both older Coeur d'Alene homes and even new construction.",
    features: [
      "Sleek, minimal profile with clean cassette housing",
      "Huge range of fabric options — sheer to blackout",
      "Premium textures including linen, woven, and metallic finishes",
      "Spring-loaded, chain, or motorized operation",
      "Can be mounted inside or outside the window frame",
      "Easy to clean and maintain",
    ],
    idealFor: [
      "Modern and contemporary home designs",
      "Home offices and media rooms (blackout options)",
      "Kitchens and bathrooms where moisture resistance matters",
      "Commercial spaces and rental properties",
      "Minimalists who want function without visual clutter",
    ],
    localContext: "Roller shades are increasingly popular in the newer construction happening around Post Falls, Rathdrum, and Hayden. The clean-lined architecture in these communities pairs naturally with the streamlined look of a quality roller shade. They're also a smart choice for rental properties — durable, easy to maintain, and universally appealing.",
    metaTitle: "Roller Shades in Northern Idaho | Modern Window Treatments",
    metaDescription: "Custom roller shades for Northern Idaho homes. Clean, modern window coverings in premium fabrics. Serving Coeur d'Alene, Post Falls, Hayden. Free in-home consultation.",
  },
  "banded-shades": {
    slug: "banded-shades",
    name: "Banded Shades",
    headline: "Control Your Light Without Closing Off the Room.",
    subheadline: "Banded shades give you the flexibility to shift between sheer filtered light and full privacy — with a distinctly modern look.",
    problem: "Most window treatments give you an either/or choice: open for light, closed for privacy. But life isn't that simple. Sometimes you want soft, diffused light in the morning and full privacy at night. Sometimes you want to see out without being seen. Traditional blinds can do this, but they collect dust, break easily, and look dated.",
    solution: "Banded shades — also called zebra shades or dual shades — use alternating bands of sheer and solid fabric on a continuous loop. When the bands align solid-to-solid, you get full privacy and light blocking. Shift them so the sheer bands overlap, and light filters through beautifully while maintaining your view. It's elegant engineering that looks as good as it works.",
    expertInsight: "Banded shades are one of the fastest-growing categories I install, especially in new homes. They photograph beautifully, which is why you see them all over design magazines. But here's the practical advice: the fabric quality varies enormously between brands. Cheap banded shades sag, the bands don't align properly after a few months, and the sheer sections look cloudy instead of crisp. The Lafayette and Norman banded shades I carry use tension systems that keep the bands perfectly aligned long-term. It's one of those products where the difference between a premium version and a budget version is immediately obvious.",
    features: [
      "Alternating sheer and solid fabric bands",
      "Seamless transition between privacy and filtered light",
      "Modern, contemporary aesthetic",
      "Available in a wide range of colors and textures",
      "Smooth, quiet operation",
      "Motorization available for convenience",
    ],
    idealFor: [
      "Living rooms and great rooms where flexible light control is key",
      "Bedrooms that need both morning light and nighttime privacy",
      "Modern and transitional home designs",
      "Street-facing windows where privacy matters during the day",
      "Anyone tired of traditional blinds but wanting similar light control",
    ],
    localContext: "Banded shades are a popular choice in the newer subdivisions around Post Falls and Hayden where contemporary design is the norm. They pair especially well with the open floor plans common in Northern Idaho new construction, where a single great room might have windows facing multiple directions with different light needs throughout the day.",
    metaTitle: "Banded Shades in Northern Idaho | Modern Zebra & Dual Shades",
    metaDescription: "Custom banded (zebra) shades for Northern Idaho homes. Flexible light control with modern style. Serving Coeur d'Alene, Post Falls, Hayden. Free in-home consultation.",
  },
  "roman-shades": {
    slug: "roman-shades",
    name: "Roman Shades",
    headline: "Add Warmth and Character That Blinds Never Could.",
    subheadline: "Roman shades bring softness, texture, and timeless elegance to any room — crafted from real fabrics that transform the feel of your space.",
    problem: "Some rooms need more than a functional window covering — they need something that adds warmth, texture, and personality. Hard blinds and minimal shades work in some spaces, but living rooms, dining rooms, and primary bedrooms often call for something softer. Something that makes the room feel finished and intentional, not just covered.",
    solution: "Roman shades fold up in elegant horizontal pleats when raised and lay flat or softly cascading when lowered. Available in an incredible range of fabrics — from crisp linens to rich textures, from subtle neutrals to bold patterns. They bring the richness of drapery with the clean functionality of a shade, and they work in traditional, transitional, and even contemporary settings.",
    expertInsight: "Roman shades are where fabric choice makes or breaks the result. I always recommend bringing fabric samples into the actual room where they'll be installed, at different times of day. A fabric that looks warm and inviting in showroom lighting can look completely different with morning light coming through it versus afternoon sun. I also steer most of my clients toward the flat fold style rather than hobbled (the puffy, cascading look) — flat folds have a more modern, tailored feel that ages better. And from an installation standpoint, Roman shades need to be precisely sized — the fabric folds need to stack evenly, which means the measurement has to account for the fold pattern. It's detail work that matters.",
    features: [
      "Elegant horizontal fabric folds when raised",
      "Vast selection of premium fabrics, textures, and patterns",
      "Flat fold and hobbled (cascading) style options",
      "Light-filtering and blackout lining available",
      "Cordless and motorized operation",
      "Can be paired with drapery panels for a layered look",
    ],
    idealFor: [
      "Living rooms and dining rooms where aesthetics are a priority",
      "Primary bedrooms that want softness and warmth",
      "Transitional and traditional home styles",
      "Rooms where you want to add texture and color through the window treatment",
      "Kitchens — especially above the sink with a flat Roman in a wipeable fabric",
    ],
    localContext: "Roman shades work beautifully in the craftsman and lodge-style homes that are iconic to the Northern Idaho landscape. In Coeur d'Alene and Sandpoint especially, homeowners gravitate toward natural linen and textured fabrics that complement the wood and stone elements common in our local architecture. They add a layer of refinement without feeling out of place.",
    metaTitle: "Roman Shades in Northern Idaho | Elegant Fabric Window Treatments",
    metaDescription: "Custom Roman shades for Northern Idaho homes. Premium fabrics, expert installation. Serving Coeur d'Alene, Post Falls, Sandpoint. Free in-home consultation.",
  },
  "shutters": {
    slug: "shutters",
    name: "Shutters",
    headline: "The One Window Treatment That Actually Adds Value to Your Home.",
    subheadline: "Plantation shutters are a permanent architectural upgrade — and with nearly 20 years of installation expertise, Mark ensures they're done right.",
    problem: "Window treatments typically depreciate the moment they're installed — they're decorating, not improving. And most of them need to be replaced every 5-10 years. If you're investing in your home, especially a home you plan to keep or a property where resale value matters, you want something that lasts and actually adds to the home's worth.",
    solution: "Plantation shutters are built to last decades. Made from premium hardwood or engineered composites, they become a permanent part of your home's architecture. They offer unmatched light control — from fully open to completely private — and they work in virtually any style of home. Shutters are consistently cited by real estate professionals as one of the window treatments that buyers notice and value.",
    expertInsight: "Shutters are where my nearly 20 years of experience matters most. Here's why: shutters require the most precise measurement of any window treatment. Every frame is custom-built to fit your specific window opening, and the tolerances are incredibly tight. A shade can be off by 1/8 inch and nobody notices. A shutter frame that's off by 1/8 inch won't close properly. I've fixed installations from other companies where the frames were built from measurements that didn't account for window frames being out of square — which happens more often than you'd think, especially in Northern Idaho homes that settle with our freeze-thaw cycles. I also help clients choose between real wood (beautiful but can warp in high-humidity areas like bathrooms) and composite (better for moisture, equally attractive). The right material in the right room makes all the difference.",
    features: [
      "Premium hardwood and engineered composite options",
      "Multiple louver sizes — 2.5\", 3.5\", and 4.5\"",
      "Full light control from open to complete privacy",
      "Custom-built to exact window specifications",
      "Adds real estate value to your home",
      "Extremely durable — built to last decades",
      "Available in painted and stained finishes",
    ],
    idealFor: [
      "Homeowners planning to stay long-term and want lasting value",
      "Properties where resale value is a consideration",
      "Larger windows where architectural impact matters",
      "Any room where you want precise light and privacy control",
      "Historically or architecturally significant homes",
    ],
    localContext: "Northern Idaho's freeze-thaw cycles can cause window frames to shift subtly over time, which is why precision measurement is critical for shutters. Mark has installed shutters in everything from historic Coeur d'Alene lakefront homes to new construction in the growing communities of Post Falls and Hayden. His measurement process accounts for these local conditions, ensuring a fit that stays true for years.",
    metaTitle: "Plantation Shutters in Northern Idaho | Custom Installation",
    metaDescription: "Custom plantation shutters for Northern Idaho homes. Expert installation with nearly 20 years experience. Serving Coeur d'Alene, Post Falls, Hayden. Lifetime installation guarantee.",
  },
  "motorization": {
    slug: "motorization",
    name: "Motorization",
    headline: "One Tap. Every Shade. Perfect Position.",
    subheadline: "Smart motorized shades you can control from your phone, your voice, or the wall — because some things should just be easy.",
    problem: "You've got windows you can't easily reach — above the stairs, in a vaulted ceiling, behind furniture. Or maybe you want all your shades to go down at sunset without getting up from the couch. Or you travel and want your home to look occupied. Manual shades are fine for accessible windows, but modern homes — and modern life — call for something smarter.",
    solution: "Motorization transforms any shade into a smart device. Open and close your window treatments with a remote, your phone, your voice through Alexa or Google Home, or programmed schedules tied to sunrise and sunset. Available for cellular shades, roller shades, Roman shades, and banded shades. Battery-powered options mean no hardwiring required in most cases.",
    expertInsight: "I've watched motorization go from a luxury add-on to one of the most requested features in the window treatment industry. And the technology is genuinely good now. Battery-powered motors from Alta and Norman last 1-2 years on a single charge and are whisper-quiet. The app integration is reliable, and setting up sunrise/sunset schedules is straightforward. My practical advice: if you're motorizing multiple shades in one room, invest in a multi-channel remote or app setup so you can control them as a group. And if you're building new construction, have your electrician run power to your window frames — hardwired motors never need battery changes and can handle heavier shades. I handle the complete setup, programming, and integration so everything works seamlessly from day one.",
    features: [
      "Control via remote, smartphone app, or voice assistant",
      "Compatible with Alexa, Google Home, and Apple HomeKit (brand dependent)",
      "Battery-powered options — no hardwiring needed",
      "Programmable schedules tied to time of day or sunrise/sunset",
      "Whisper-quiet motor operation",
      "Available for most shade types",
      "Group control for multiple shades in one room",
    ],
    idealFor: [
      "Hard-to-reach windows — vaulted ceilings, above stairs, behind furniture",
      "Smart home setups with existing voice assistant integration",
      "Homeowners who want automated sunrise/sunset schedules",
      "New construction where hardwired power can be planned in advance",
      "Anyone who values convenience and modern functionality",
      "Vacation homes and rental properties for security (occupied appearance)",
    ],
    localContext: "Motorization is increasingly popular in Northern Idaho, especially in the new construction happening around Post Falls and Rathdrum. Many of these homes have great rooms with soaring ceilings and large windows that would be impractical to operate manually. For lakefront homes in Coeur d'Alene and Sandpoint, automated sunset schedules mean your privacy shades lower exactly when you need them without lifting a finger.",
    metaTitle: "Motorized Shades in Northern Idaho | Smart Window Treatments",
    metaDescription: "Smart motorized window treatments for Northern Idaho homes. Voice control, app control, automated schedules. Serving Coeur d'Alene, Post Falls, Hayden. Free consultation.",
  },
};
